sudo: required
services:
  - docker

before_install:
  - docker build -t harshvb7/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run harshvb7/react-test npm test -- --coverage

after_success:
  - docker build -t harshvb7/multi-client ./client
  - docker build -t harshvb7/multi-nginx ./nginx
  - docker build -t harshvb7/multi-server ./server
  - docker build -t harshvb7/multi-worker ./worker
  # docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker
  - docker push harshvb7/multi-client
  - docker push harshvb7/multi-nginx
  - docker push harshvb7/multi-server
  - docker push harshvb7/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-974631192716
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
